Starting
Trying...
func(): calling f()
f(): raising exception-1...
func(): caught exception-1
Fini!
Starting
Trying...
func(): calling f()
f(): raising exception-2...
func(): caught exception-2, raising it again...
Caught exception-2
Fini!
Starting
Trying...
func(): calling f()
f(): raising exception-3...
func(): caught exception-3, raising it again...
Fini!
faux core dump with exception-3
